academico/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('alunos/', views.alunos, name='alunos'),
    path('cursos/', views.cursos, name='cursos'),
    path('cadastrar_aluno/', views.cadastrar_aluno, name='cadastrar_aluno'),
    path('cadastrar_curso/', views.cadastrar_curso, name='cadastrar_curso'),
    path('editar_aluno/<int:id>/', views.editar_aluno, name='editar_aluno'),
    path('editar_curso/<int:id>/', views.editar_curso, name='editar_curso'),
]

contato/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.contato, name='contato'),  
]

projeto_academico/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('academico.urls')),
    path('contato/', include('contato.urls')),
]

academico/models.py
from django.db import models

GENERO_CHOICES = [
    ('M', 'Masculino'),
    ('F', 'Feminino'),
    ('NB', 'Não-binário'),
    ('O', 'Outro'),
]

ESTADO_CIVIL_CHOICES = [
    ('S', 'Solteiro'),
    ('C', 'Casado'),
    ('D', 'Divorciado'),
    ('V', 'Viúvo'),
]

ESCOLARIDADE_CHOICES = [
    ('fun', 'Fundamental'),
    ('med', 'Médio'),
    ('sup', 'Superior'),
    ('pos', 'Pós-graduação'),
    ('mes', 'Mestrado'),
    ('dou', 'Doutorado'),
]


class Curso(models.Model):
    nome = models.CharField(max_length=100)

    def __str__(self):
        return self.nome

class Aluno(models.Model):
    nome = models.CharField(max_length=100)
    data_nascimento = models.DateField()
    cpf = models.CharField(max_length=14, unique=True)
    genero = models.CharField(max_length=2, choices=GENERO_CHOICES)
    estado_civil = models.CharField(
        max_length=30, choices=ESTADO_CIVIL_CHOICES)
    escolaridade = models.CharField(
        max_length=50, choices=ESCOLARIDADE_CHOICES)
    curso = models.ForeignKey(Curso, on_delete=models.CASCADE)

    def __str__(self):
        return self.nome

contato/models.py
from django.db import models

# Create your models here.

academico/forms.py
from django import forms
from .models import Curso, Aluno

# Formulário para Curso


class CursoForm(forms.ModelForm):
    class Meta:
        model = Curso  # Aqui vamos dizer que o formulário vai usar o modelo Curso
        # Aqui vamos dizer quais campos do modelo Curso queremos usar no formulário
        fields = ['nome']

# Formulário para Aluno


class AlunoForm(forms.ModelForm):
    data_nascimento = forms.DateField(
        widget=forms.DateInput(attrs={'type': 'date'}, format='%Y-%m-%d'),
        input_formats=['%Y-%m-%d']
    )

    class Meta:
        model = Aluno  # Aqui vamos dizer qual modelo esse formulário vai usar
        fields = ['nome', 'data_nascimento', 'cpf', 'genero',
                  'estado_civil', 'escolaridade', 'curso']
        # Aqui vamos dizer quais campos do modelo aluno queremos usar no formulário

contato/forms.py
from django import forms

class ContatoForm(forms.Form):
    nome = forms.CharField(label='Nome', max_length=100)
    email = forms.EmailField(label='Email')
    assunto = forms.CharField(label='Assunto', max_length=100)
    mensagem = forms.CharField(label='Mensagem', widget=forms.Textarea)

academico/views.py
from django.shortcuts import render
from .models import Aluno, Curso
from .forms import CursoForm, AlunoForm
from django.shortcuts import redirect

# Create your views here.


def index(request):
    return render(request, 'academico/index.html')


def alunos(request):
    alunos = Aluno.objects.all()
    dados = {
        'alunos': alunos,
    }
    return render(request, 'academico/lista_alunos.html', dados)


def cursos(request):
    cursos = Curso.objects.all()
    dados = {
        'cursos': cursos,
    }
    return render(request, 'academico/lista_cursos.html', dados)


def cadastrar_aluno(request):

    if request.method == 'POST':
        form = AlunoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('alunos')
    else:
        form = AlunoForm()
        dados = {
            'form': form,
        }
    return render(request, 'academico/cadastrar_aluno.html', dados)


def cadastrar_curso(request):

    if request.method == 'POST':
        form = CursoForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('cursos')  
    else:
        form = CursoForm()
        dados = {
            'form': form,
        }
    return render(request, 'academico/cadastrar_curso.html', dados)


def editar_aluno(request, id):

    try:
        aluno = Aluno.objects.get(id=id)
    except:
        return redirect('alunos')

    if request.method == 'POST':
        form = AlunoForm(request.POST, instance=aluno)
        if form.is_valid():
            form.save()
            return redirect('alunos')

    # form vai receber um formulário com os dados do aluno selecionado.
    form = AlunoForm(instance=aluno)

    # Montamos o dicionário com os dados para ser passado para o template.
    dados = {
        'form': form,
        'aluno': aluno,
    }

    return render(request, 'academico/editar_aluno.html', dados)


def editar_curso(request, id):

    try:
        curso = Curso.objects.get(id=id)
    except:
        return redirect('cursos')

    if request.method == 'POST':
        form = CursoForm(request.POST, instance=curso)
        if form.is_valid():
            form.save()
            return redirect('cursos')

    form = CursoForm(instance=curso)

    dados = {
        'form': form,
        'curso': curso,
    }

    return render(request, 'academico/editar_curso.html', dados)

contato/views.py
from django.shortcuts import render
from . import forms
from django.core.mail import send_mail


def contato(request):

    if request.method == 'POST':
        form = forms.ContatoForm(request.POST)
        if form.is_valid():
            nome = form.cleaned_data['nome']
            email = form.cleaned_data['email']
            assunto = form.cleaned_data['assunto']
            mensagem = form.cleaned_data['mensagem']

            corpo_email = f"Mensagem de: {nome}\n\n Email: {email}\n\n Mensagem: {mensagem}"

            send_mail(
                assunto,
                corpo_email,
                email,  # remetente
                ['linden.denisrenan@gmail.com'],  # destinatário
            )

            form = forms.ContatoForm()
            dados = {
                'form': form,
                'mensagem_enviada': True,
                'mensagem': 'Mensagem enviada com sucesso!',
            }

    else:
        # Se o método não for POST, cria um novo formulário vazio
        form = forms.ContatoForm()
        dados = {
            'form': form,
        }

    return render(request, 'contato/contato.html', dados)

academico/templates/academico/cadastrar_aluno.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Aluno</title>
</head>
<body>
    
    <h1>Cadastro de Aluno</h1>

    <form method="post" action="{% url 'cadastrar_aluno' %}">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit">Cadastrar Aluno</button>
    </form>

    <p><a href="{% url 'index' %}">Voltar para Menu</a></p>

    {% if error %}
        <p style="color: red;">{{ error }}</p>
    {% endif %}

</body>
</html>

academico/templates/academico/cadastrar_curso.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cadastro de Curso</title>
</head>
<body>
    
    <h1>Cadastro de Curso</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Cadastrar Curso</button>

    </form>

    <p><a href="{% url 'index' %}">Voltar para Menu</a></p>

    

</body>
</html>

academico/templates/academico/editar_aluno.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Aluno</title>
</head>
<body>
    
    <h1>Edição de Aluno</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit">Salvar Alterações</button>
        <p><a href="{% url 'alunos' %}"> Voltar</a></p>
    </form>

</body>
</html>

academico/templates/academico/editar_curso.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edição de Curso</title>
</head>
<body>
    
    <h1>Editar Curso</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Salvar Alterações</button>

    </form>

    <p><a href="{% url 'index' %}">Voltar para Menu</a></p>

    

</body>
</html>

academico/templates/academico/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index de Acadêmico</title>
</head>
<body>
    <h1>Index de Acadêmico</h1>

    <ul>
        <p>Escolha uma opção:</p>
        <li><a href=" {% url 'cadastrar_aluno' %}">Cadastro de Aluno</a></li>
        <li><a href=" {% url 'cadastrar_curso' %}">Cadastro de Curso</a></li>
        <li><a href=" {% url 'alunos' %}">Lista de Alunos</a></li>
        <li><a href=" {% url 'cursos' %}">Lista de Cursos</a></li>
        <li><a href=" {% url 'contato' %}">Contato</a></li>
    </ul>

    </body>
</html>

academico/templates/academico/lista_alunos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Lista de Alunos</title>
</head>
<body>
    <h1>Lista de Alunos</h1>
    <table border="1" cellpadding="5" cellspacing="3">
        <tr>
            <th>Nome</th>
            <th>Curso</th>
            <th>Gênero</th>
            <th>Escolaridade</th>
            <th>Estado Civil</th>
            <th>Nascimento</th>
            <th>Editar</th>
        </tr>
        {% for aluno in alunos %}
        <tr>
            <td>{{ aluno.nome }}</td>
            <td>{{ aluno.curso }}</td>
            <td>{{ aluno.get_genero_display }}</td>
            <td>{{ aluno.get_escolaridade_display }}</td>
            <td>{{ aluno.get_estado_civil_display }}</td>
            <td>{{ aluno.data_nascimento|date:"d/m/Y" }}</td>
            <td><a href="{% url 'editar_aluno' aluno.id %}">Editar</a></td>
        
        </tr>
        {% endfor %}
    </table>

    <p><a href="{% url 'index' %}">Voltar para Menu</a></p>

</body>
</html>

academico/templates/academico/lista_cursos.html
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Cursos</title>
</head>
<body>
    <h1>Lista de Cursos</h1>
    <table border="1" cellpadding="5" cellspacing="3">
        <thead>
            <tr>
                <th>Nome</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            {% for curso in cursos %}
            <tr>
                <td>{{ curso.nome }}</td>
                <td>
                    <a href="{% url 'editar_curso' curso.id %}">Editar</a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3">Nenhum curso cadastrado.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
    <p><a href="{% url 'index' %}">Voltar para Menu</a></p>
</body>
</html>

contato/templates/contato/contato.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Contato</title>
</head>
<body>
    <h1>Bem-vindo à página de contato</h1>

    {% if mensagem_enviada %}
        {{ mensagem }}
    {% endif %}

    
    <form method="post"> 
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Enviar</button>
        <button type="reset">Limpar</button>

    </form>

    <p><a href="{% url 'index' %}">Voltar para Menu</a></p>

</body>
</html>